package main

import (
	"crypto/rand"
	"flag"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/kklash/mnemonikey"
	"github.com/kklash/mnemonikey/mnemonic"
)

var DefaultName = "anonymous"

type GenerateOptions struct {
	Name      string
	Email     string
	WordCount uint
}

var GenerateCommand = &Command[GenerateOptions]{
	Name: "mnemonikey generate",
	AddFlags: func(flags *flag.FlagSet, opts *GenerateOptions) {
		flags.StringVar(&opts.Name, "name", DefaultName, "Display name for the PGP key user identifier.")
		flags.StringVar(&opts.Email, "email", "", "Email for the PGP key user identifier. (optional)")

		flags.UintVar(
			&opts.WordCount,
			"count",
			mnemonikey.MinMnemonicSize,
			fmt.Sprintf(
				"Number of words in the recovery mnemonic. Must be at least %d to be secure. (optional)",
				mnemonikey.MinMnemonicSize,
			),
		)
	},
	Execute: func(opts *GenerateOptions, args []string) error {
		return generateAndPrintKey(opts)
	},
}

func generateAndPrintKey(opts *GenerateOptions) error {
	name := strings.TrimSpace(opts.Name)
	email := strings.TrimSpace(opts.Email)

	if opts.WordCount < mnemonikey.MinMnemonicSize {
		return fmt.Errorf("%w: invalid word count %d", ErrPrintUsage, opts.WordCount)
	}

	totalBitCount := mnemonic.BitsPerWord * opts.WordCount
	seedBitCount := totalBitCount - uint(mnemonikey.BirthdayBitCount)
	seed, err := mnemonikey.GenerateSeed(rand.Reader, seedBitCount)
	if err != nil {
		return err
	}

	birthday := time.Now()

	keyPair, err := mnemonikey.NewDeterministicKeyPair(seed, name, email, birthday, time.Time{})
	if err != nil {
		return err
	}

	pgpArmorKey, err := keyPair.EncodePGPArmor([]byte(nil))
	if err != nil {
		return err
	}

	recoveryMnemonic, err := keyPair.EncodeMnemonic()
	if err != nil {
		return err
	}

	fmt.Printf("Generated OpenPGP private key with %d bits of entropy:\n\n%s\n\n", seedBitCount, pgpArmorKey)

	// TODO print debug info about key
	// TODO print in color

	fmt.Printf("This is the key mnemonic which can be used to deterministically recover the private key:\n\n")
	printMnemonic(recoveryMnemonic)
	fmt.Printf("\nSave this phrase in a secure place, preferably offline on paper.\n\n")

	fmt.Printf(
		"You should also save the name and email address used to create the key. " +
			"If you later try to recover the key with the same mnemonic phrase but " +
			"a different name or email, it will derive the same key, but with a different " +
			"key fingerprint. To anyone verifying signatures using the old public key, " +
			"signature generated by the recovered key will not look correct.\n\n",
	)

	fmt.Printf("Name:  %q\n", name)
	fmt.Printf("Email: %q\n", email)

	return nil
}

func printMnemonic(words []string) {
	for i, word := range words {
		humanIndex := strconv.Itoa(i + 1)
		spacing := strings.Repeat(" ", 4-len(humanIndex))
		fmt.Printf("%s:%s%s\n", humanIndex, spacing, word)
	}
}
